# Generated by Django 3.2.1 on 2022-08-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20220814_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='profile.png', upload_to='images/'),
        ),
    ]
