# Generated by Django 3.2.1 on 2022-08-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20220814_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Romatic', 'Romantic'), ('Adventure', 'Adventure'), ('Horror', 'Horror'), ('Scientific Fictions', 'Scientific Fictions')], max_length=250),
        ),
    ]
